### ISSUE TITLE
Ability to run applications in administrative mode

### ISSUE THREAD

**Issue by thecodejunkie** [spectresystems/jarvis#39] opened 2018-01-05 21:42 UTC
Sometimes you need to run an application, with elevated privileges. Would be nice if we had that ability with Jarvis - preferably without having to resort to using the mouse. Pretty sure this is something you have on your mental road map, but putting it here part as a reminder and part so other people can 👍 to help prioritize

**Comment by patriksvensson** [comment] 2018-01-10 11:26
Duplicate of #29

**Closed by patriksvensson** 2018-01-10 11:26 UTC
Labels: duplicate
